import Head from 'next/head';
import { motion } from 'framer-motion';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { Box, Flex, Heading, Text } from '@chakra-ui/react';
import Sidebar from '~/components/sidebar/Sidebar';
import { UserRole } from '@prisma/client';
import { useSession } from 'next-auth/react';
import { withSession } from '~/server/auth/withSession';
import { adminRoutes, mentorRoutes, eoRoutes } from '~/utils/routes';

export const getServerSideProps = withSession({ force: true });

export default function WelcomePage() {
  const { data: session } = useSession();

  const routes =
    session?.user.role === UserRole.ADMIN
      ? adminRoutes
      : session?.user.role === UserRole.MENTOR
      ? mentorRoutes
      : session?.user.role === UserRole.EO
      ? eoRoutes
      : [];

  return (
    <>
      <Head>
        <title>Welcome - KAT ITB 2023</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Sidebar routes={routes} />
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5 }}
      >
        <Box
          float='right'
          minHeight='100vh'
          height='100%'
          overflow='auto'
          position='relative'
          maxHeight='100%'
          w='calc( 100% - 298px )'
          maxWidth='calc( 100% - 290px )'
        >
          <Box
            mr={6}
            my={'2vh'}
            bg='#F9F9F9'
            borderLeftRadius={25}
            borderRightRadius={25}
            height={'96vh'}
            px='50px'
            py={'30px'}
          >
            <Flex
              justifyContent={'center'}
              alignItems={'center'}
              flexGrow={1}
              height={'100%'}
              flexDirection={'column'}
            >
              <Heading>Welcome to Internal Dashboard</Heading>
              <Text fontSize={'2xl'}>Click sidebar menu to start</Text>
            </Flex>
          </Box>
          {process.env.NODE_ENV !== 'production' && (
            <Box>
              <ReactQueryDevtools initialIsOpen={false} />
            </Box>
          )}
        </Box>
      </motion.div>
    </>
  );
}
