import Head from 'next/head';
import { motion } from 'framer-motion';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { Box } from '@chakra-ui/react';
import Sidebar from '~/component/sidebar/Sidebar';
import { adminRoutes, mentorRoutes } from '~/utils/routes';

interface Props {
  title: string;
  children?: React.ReactNode;
}

export default function Layout({ title, children }: Props) {
  return (
    <>
      <Head>
        <title>{title ? `${title} - KAT ITB 2023` : `KAT ITB 2023`}</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* TODO: Add navbar */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5 }}
      >
        <Box px={{ base: 7, lg: 12 }} py={5}>
          {children}
          {process.env.NODE_ENV !== 'production' && (
            <Box>
              <ReactQueryDevtools initialIsOpen={false} />
            </Box>
          )}
        </Box>
      </motion.div>
      {/* TODO: Add footer */}
    </>
  );
}

interface ContentLayoutProps extends Props {
  type: 'mentor' | 'admin';
}

export function ContentLayout(props: ContentLayoutProps) {
  const { children, title } = props;
  return (
    <>
      <Head>
        <title>{title ? `${title} - KAT ITB 2023` : `KAT ITB 2023`}</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5 }}
      >
        <Box>
          <Sidebar
            routes={props.type === 'admin' ? adminRoutes : mentorRoutes}
          />
          <Box
            float='right'
            minHeight='100vh'
            height='100%'
            overflow='auto'
            position='relative'
            maxHeight='100%'
            w='calc( 100% - 298px )'
            maxWidth='calc( 100% - 290px )'
          >
            <Box mx='auto' p='0px' minH='100vh'>
              {children}
            </Box>
          </Box>
        </Box>
      </motion.div>
    </>
  );
}
