import Head from 'next/head';
import { motion } from 'framer-motion';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { Box } from '@chakra-ui/react';
import Sidebar from '~/component/sidebar/Sidebar';
import { adminRoutes, mentorRoutes } from '~/utils/routes';

interface Props {
  title: string;
  children?: React.ReactNode;
  type: 'mentor' | 'admin';
}

export default function Layout({ title, children, type }: Props) {
  return (
    <>
      <Head>
        <title>{title ? `${title} - KAT ITB 2023` : `KAT ITB 2023`}</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Sidebar routes={type === 'admin' ? adminRoutes : mentorRoutes} />
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5 }}
      >
        <Box>
          <Box
            float='right'
            minHeight='100vh'
            height='100%'
            overflow='auto'
            position='relative'
            maxHeight='100%'
            w='calc( 100% - 298px )'
            maxWidth='calc( 100% - 290px )'
          >
            {children}
            {process.env.NODE_ENV !== 'production' && (
              <Box>
                <ReactQueryDevtools initialIsOpen={false} />
              </Box>
            )}
          </Box>
        </Box>
      </motion.div>
      {/* TODO: Add footer */}
    </>
  );
}
